### PR TITLE
vec-379 Support AVS 0.11.x

### PR DESCRIPTION
**Pull request by dwelch-spike**
- Adds number of vectors and vertices in the index list/get methods.
- Allows for infinite cache expiration using -1
- Allow for caching vector records
- Allow toggling vector integrity checks
- Make multiple fields optional
- Rename multiple fields

Summary of proto changes and their implications…

Adds…

    indexStatusResponse

        indexHealerVectorRecordsIndexed

        indexHealerVerticesValid

    hnswParams

        recordCachingParams

        enableVectorIntegrityCheck

    indexUpdateParams

        recordCachingParams

        enableVectorIntegrityCheck

    HnswBatchingParams

        maxReindexRecords

        reindexInterval

Changes the type of…

    HnswCachingParams

        expiry from uint64 to int64 (this BREAKS the grpc protocol making this api version incompatible with older clients and older servers)

Renames (these are all BREAKING changes for applications consuming the go client)

    HnswIndexUpdate

        cachingParams → indexCachingParams

    HnswParams

        cachingParams → indexCachingParams

    HnswBatchingParams

        maxRecords → maxIndexRecords

        interval → indexInterval

Makes Optional (these are all BREAKING changes for applications consuming the go client)

    PutRequest

        WriteType

    ProjectionFilter

        ProjectionType

    IndexDefinition

        IndexType

        VectorDistanceMetric

### CODE REVIEW

**Review by rahul-aerospike — COMMENTED** [review]
Is there a reason we are committing generated proto files to the repository? Since this is a compiled language, I would assume it's possible to generate the proto files during the artifact generation process, rather than committing them. @dwelch-spike

**Comment by dwelch-spike** [comment]
> Is there a reason we are committing generated proto files to the repository? Since this is a compiled language, I would assume it's possible to generate the proto files during the artifact generation process, rather than committing them. @dwelch-spike

It's so that consumers of this library can use it more easily. In Golang, libs aren't built into artifacts like wheels in Python, instead source code is pulled in directly with the `go get` command. With the generated files in the repo, the code will work out of the box

**Comment by rahul-aerospike** [comment]
@dwelch-spike Got it, that makes sense. In a future release, it might be better to organize the proto files into a separate directory from the generated files.

**Review by rahul-aerospike — APPROVED** [review]
Every thing else looks good to me. Please wait for yevgeny's approval before merging, if possible.

**Review by reugn — APPROVED** [review]

**Pull request merged**
